apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
     matchLabels:
         app: web-server
  template:
    metadata:
      labels:
        app: web-server
        version: "1.0"
    spec:
      containers:
        - name: web-server
          image: master.mine.com/holder/mine-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      serviceAccountName: default            
      imagePullSecrets:
           - name: regcred


---

apiVersion: v1
kind: Service
metadata:
 name: web-server
 namespace: default
spec:
 type: NodePort
 selector:
   app: web-server
   version: "1.0"
 ports:
 - port: 8080
   targetPort: 8080
   protocol: TCP
   nodePort: 30010 
